#!/usr/bin/env bash

proc_file='/proc/sys/vm/drop_caches'

if [[ $(id -u) -ne 0 ]]; then
    printf 'Error: Insufficient permissions!\n'
    printf 'Ensure you are running this command with root permissions\n'
    exit 1
fi >&2

if [[ -e $proc_file ]]; then
	if tee $proc_file <<<'1' >/dev/null; then
		printf 'Successfully dropped caches\n'
	else
		printf 'Error: An error occurred while writing to %s\n' "$proc_file" >&2
		exit 1
	fi
fi

exit 0
